### ISSUE TITLE
Unrecognized import path "go.buf.build/grpc/go/prometheus/prometheus

### ISSUE THREAD

**Issue by thakurmiti** [grafana/xk6-sql#45]
We're getting error while running xk6 build --with github.com/grafana/xk6-sql command. It was working fine till yesterday but today it's throwing below error. We didn't make any code change.

I even tried changing the URL to github.com/stefnedelchevbrady/xk6-sql-with-oracle but still getting same error.

Step #1: k6 imports
Step #1: 	go.k6.io/k6/cmd imports
Step #1: 	github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite imports
Step #1: 	go.buf.build/grpc/go/prometheus/prometheus: unrecognized import path "go.buf.build/grpc/go/prometheus/prometheus": https fetch: Get "https://go.buf.build/grpc/go/prometheus/prometheus?go-get=1": dial tcp: lookup go.buf.build on 169.254.169.254:53: no such host

**Comment by thakurmiti** [comment]
Update:
I was able to find this workaround in the meantime: https://community.grafana.com/t/unable-to-build-custom-k6-binary-with-extensions/100481/3

**Comment by javaducky** [comment]
This has been fixed given https://github.com/grafana/xk6-sql/pull/46.
