### ISSUE TITLE
mssql - use official Microsoft driver

### ISSUE THREAD

**Issue by cwegener** [grafana/xk6-sql#48]
Microsoft has created an official fork of https://github.com/denisenkom/go-mssqldb at https://github.com/microsoft/go-mssqldb in agreement with the original project maintainers https://github.com/denisenkom/go-mssqldb/issues/729

Since then, there have been plenty of fixes and enhancement delivered under the new Microsoft umbrella and many official versioned releases.

The original project is receiving the minimum maintenance effort.

xk6-sql should adopt the new fork of go-mssqldb in favor of the legacy driver.

**Comment by javaducky** [comment]
@cwegener thank you for raising this issue! We'll get that updated.
