### ISSUE TITLE
uuid returned as an array of numbers for MS SQL

### ISSUE THREAD

**Issue by adumitreseibogdan** [grafana/xk6-sql#60]
Hi,

I'm connecting to a MS SQL database, when I query a table, the columns that have an uuid stored are returned as an array of numbers, for example for:

“Id”:“31834ec8-d1b5-48ee-8f2d-36072101aa74”
is returned as:
“Id”:[200,78,131,49,181,209,238,72,143,45,54,7,33,1,170,116]

**Comment by adumitreseibogdan** [comment]
gonna close this issue as it seems to be the normal behavior, the array of numbers represents ASCII codes, that need to be converted back to UUID format

**Comment by vipul-mykaarma** [comment]
@adumitreseibogdan any ways to achieve the same, facing the same issue
