### ISSUE TITLE
k6/x/sql still unknown after creating binary: GoError: unknown module: k6/x/sql

### ISSUE THREAD

**Issue by IamKoN** [grafana/xk6-sql#65]
k6 script, vendor.js:

```
import http from "k6/http";
import { check, sleep } from "k6";
import jsonpath from "https://jslib.k6.io/jsonpath/1.0.2/index.js"; 
import sql from 'k6/x/sql';

```
project directory:
![image](https://github.com/grafana/xk6-sql/assets/30881124/cf16491c-8dc4-4768-a9fa-bb371616e628)

cmds used to build xk6-sql binary: 
```
xk6 build --with github.com/grafana/xk6-sql
xk6 build master --with github.com/grafana/xk6-sql
```
both work to create the binary in the working dir, but when running `k6 run vendor.js`
I get the same error each time:
```
ERRO[0000] GoError: unknown module: k6/x/sql
at go.k6.io/k6/js.(*requireImpl).require-fm (native)
at file:///C:/repos/.../app/k6_test/vendor.js:4:0(44)  hint="script exception"
```

**Comment by kempsterc** [comment]
Try

./k6 run vendor.js

If you run ./k6 version 
What do you get?

**Comment by IamKoN** [comment]
> Try
> 
> ./k6 run vendor.js
> 
> If you run ./k6 version What do you get?

k6.exe v0.50.0 (go1.22.2, windows/amd64)
Extensions:
  github.com/grafana/xk6-sql v0.4.0, k6/x/sql [js]
  
`./k6 run vendor.js` worked, thank you! Not sure why that made the difference, but much appreciated.
