### ISSUE TITLE
Support of TLS certificates for K6 SQL plugin

### ISSUE THREAD

**Issue by Amar-C** [grafana/xk6-sql#70]
[go-sql-driver](https://pkg.go.dev/github.com/go-sql-driver/mysql#RegisterTLSConfig)  supports TLS certificates. Can we extend the support to this plugin

**Comment by Amar-C** [comment]
@szkiba Looks like the [PR-71](https://github.com/grafana/xk6-sql/pull/71) for this is merged. Can you release a new version of the plugin?

**Comment by szkiba** [comment]
> Looks like the https://github.com/grafana/xk6-sql/pull/71 for this is merged. Can you release a new version of the plugin?

@Amar-C Done [v0.4.1](https://github.com/grafana/xk6-sql/releases/tag/v0.4.1)
Thank you for your contribution!
